# Generated by Django 3.0.8 on 2020-07-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hobbies',
            field=models.TextField(max_length=100),
        ),
    ]
