# Generated by Django 3.0.8 on 2020-07-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='name',
        ),
    ]
