# Generated by Django 3.0.8 on 2020-07-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200729_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
