# Generated by Django 3.0.8 on 2020-08-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='profession',
            field=models.CharField(default='', max_length=500),
        ),
    ]
