# Generated by Django 3.0.8 on 2020-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200803_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='hobbies',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='profession',
            field=models.CharField(max_length=500),
        ),
    ]
